version: '3.8'

services:
  spark-master:
    build: .
    container_name: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - .:/opt/project
    environment:
      - INIT_DAEMON_STEP=setup_spark
    env_file:
      - ./config/hadoop.env

  spark-worker:
    build: .
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - .:/opt/project
    env_file:
      - ./config/hadoop.env

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=green_it
      - DOCKER_INFLUXDB_INIT_BUCKET=pollution_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8UQhpkFFUhayrciEAnvRzEpobV1T6svqiZcu-dSAg7rfJu44ykeMwciJ9bmaofjHUDopZfbjTlisObPOTgLbdw==

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: